wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1643903245
    t:
      4: 3.9.6
      5: 0.12.7
      8:
      - 1
      - 5
