wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1644502411
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 19
      4: 3.9.6
      5: 0.12.7
      8:
      - 5
algorithm:
  desc: null
  value: ARS
learning_timestep:
  desc: null
  value: 10000
policy:
  desc: null
  value: MlpPolicy
seed:
  desc: null
  value: 666
