wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1649238640
    t:
      1:
      - 1
      - 2
      - 3
      2:
      - 1
      - 2
      - 3
      4: 3.9.6
      5: 0.12.7
      8:
      - 5
